defaults:
  - predictor: bert_with_handcrafted_feature_predictor
  - validator: cross_validator
  - _self_

timestamp: ${now:%Y-%m-%d}/${now:%H-%M-%S}
cwd: ${hydra:runtime.cwd}

hydra:
  job:
    chdir: True
