name: continuous-integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry lock
          poetry --no-root install
      - uses: jamescurtin/isort-action@master
      - name: Lint with flake8
        run: |
          poetry run flake8
      - name: Lint with static type checker mypy
        run: |
          poetry run mypy .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Coverage report
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
