name: continuous-integraion

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
