name: continuous-integration

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.13
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry lock
          poetry install
      - uses: jamescurtin/isort-action@master
      - name: Lint with flake8
        run: |
          poetry run flake8
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Coverage report
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
