name: kaggle-submission

on:
  pull_request:
    branches:
      - main
    types: [closed]


jobs:
  kaggle-api:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Authenticate to Kaggle
        run: |
          mkdir ~/.kaggle
          echo ${{ secrets.KAGGLE }} >> ~/.kaggle/kaggle.json
      - name: Push kernel
        run: kaggle kernels push -p src/
